// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "gui.h"

void GUI::cb_DBG_i(Fl_Button*, void*) {
  DBG_cb();
}
void GUI::cb_DBG(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_DBG_i(o,v);
}

void GUI::cb_PlayButton_i(Fl_Return_Button*, void*) {
  Play_cb();
}
void GUI::cb_PlayButton(Fl_Return_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_PlayButton_i(o,v);
}

//my mess

void GUI::cb_SM1_i(Fl_Button*, void*) {
    SM1_cb();
}
void GUI::cb_SM1(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_SM1_i(o,v);
}

void GUI::cb_SM2_i(Fl_Button*, void*) {
    SM2_cb();
}
void GUI::cb_SM2(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_SM2_i(o,v);
}

void GUI::cb_SM3_i(Fl_Button*, void*) {
    SM3_cb();
}
void GUI::cb_SM3(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_SM3_i(o,v);
}

void GUI::cb_AmbPlus_i(Fl_Button*, void*) {
    AmbPlus_cb();
}
void GUI::cb_AmbPlus(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_AmbPlus_i(o,v);
}

void GUI::cb_AmbMinus_i(Fl_Button*, void*) {
    AmbMinus_cb();
}
void GUI::cb_AmbMinus(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_AmbMinus_i(o,v);
}

void GUI::cb_SpecPlus_i(Fl_Button*, void*) {
    SpecPlus_cb();
}
void GUI::cb_SpecPlus(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_SpecPlus_i(o,v);
}

void GUI::cb_SpecMinus_i(Fl_Button*, void*) {
    SpecMinus_cb();
}
void GUI::cb_SpecMinus(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_SpecMinus_i(o,v);
}


void GUI::cb_Up_i(Fl_Button*, void*) {
    Up_cb();
}
void GUI::cb_Up(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_Up_i(o,v);
}

void GUI::cb_Down_i(Fl_Button*, void*) {
    Down_cb();
}
void GUI::cb_Down(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_Down_i(o,v);
}

void GUI::cb_Left_i(Fl_Button*, void*) {
    Left_cb();
}
void GUI::cb_Left(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_Left_i(o,v);
}

void GUI::cb_Right_i(Fl_Button*, void*) {
    Right_cb();
}
void GUI::cb_Right(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_Right_i(o,v);
}

void GUI::cb_Front_i(Fl_Button*, void*) {
    Forward_cb();
}
void GUI::cb_Front(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_Front_i(o,v);
}

void GUI::cb_Back_i(Fl_Button*, void*) {
    Backward_cb();
}
void GUI::cb_Back(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_Back_i(o,v);
}
void GUI::cb_ZPlus_i(Fl_Button*, void*) {
    ZPlus_cb();
}
void GUI::cb_ZPlus(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_ZPlus_i(o,v);
}
void GUI::cb_ZMinus_i(Fl_Button*, void*) {
    ZMinus_cb();
}
void GUI::cb_ZMinus(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_ZMinus_i(o,v);
}

void GUI::cb_PanPlus_i(Fl_Button*, void*) {
    TiltPlus_cb();
}
void GUI::cb_PanPlus(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_PanPlus_i(o,v);
}

void GUI::cb_PanMinus_i(Fl_Button*, void*) {
    TiltMinus_cb();
}
void GUI::cb_PanMinus(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_PanMinus_i(o,v);
}

void GUI::cb_TiltPlus_i(Fl_Button*, void*) {
    PanPlus_cb();
}
void GUI::cb_TiltPlus(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_TiltPlus_i(o,v);
}

void GUI::cb_TiltMinus_i(Fl_Button*, void*) {
    PanMinus_cb();
}
void GUI::cb_TiltMinus(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_TiltMinus_i(o,v);
}

void GUI::cb_RollPlus_i(Fl_Button*, void*) {
    RollPlus_cb();
}
void GUI::cb_RollPlus(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_RollPlus_i(o,v);
}

void GUI::cb_RollMinus_i(Fl_Button*, void*) {
    RollMinus_cb();
}
void GUI::cb_RollMinus(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_RollMinus_i(o,v);
}






#include "scene.h"

GUI::GUI() {
  { uiw = new Fl_Double_Window(470, 197, "GUI");
    uiw->user_data((void*)(this));
    { Fl_Button* o = new Fl_Button(15, 15, 85, 40, "DBG");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_DBG);
    } // Fl_Button* o
    { Fl_Return_Button* o = new Fl_Return_Button(15, 80, 85, 100, "Play");
      o->callback((Fl_Callback*)cb_PlayButton);
    } // Fl_Return_Button* o

    //added buttons
    { Fl_Button* o = new Fl_Button(345, 5, 40, 21, "SM1");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_SM1);
    }

    { Fl_Button* o = new Fl_Button(345, 27, 40, 21, "SM2");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_SM2);
    }

    { Fl_Button* o = new Fl_Button(345, 52, 40, 21, "SM3");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_SM3);
    }

    { Fl_Button* o = new Fl_Button(390, 5, 65, 21, "Ambient +");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_AmbPlus);
    }

    { Fl_Button* o = new Fl_Button(390, 29, 65, 21, "Ambient -");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_AmbMinus);
    }

    { Fl_Button* o = new Fl_Button(390, 52, 65, 21, "Specular +");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_SpecPlus);
    }

    { Fl_Button* o = new Fl_Button(390, 73, 65, 21, "Specular -");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_SpecMinus);
    }

    //

    { Fl_Button* o = new Fl_Button(155, 5, 40, 21, "Up");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_Up);
    }
    { Fl_Button* o = new Fl_Button(155, 52, 40, 21, "Down");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_Down);
    }
    { Fl_Button* o = new Fl_Button(115, 26, 40, 21, "Left");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_Left);
    }
    { Fl_Button* o = new Fl_Button(195, 26, 40, 21, "Right");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_Right);
    }
    { Fl_Button* o = new Fl_Button(265, 5, 40, 21, "Front");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_Front);
    }
    { Fl_Button* o = new Fl_Button(265, 52, 40, 21, "Back");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_Back);
    }
    { Fl_Button* o = new Fl_Button(305, 5, 40, 21, "Z+");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_ZPlus);
    }
    { Fl_Button* o = new Fl_Button(305, 52, 40, 21, "Z-");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_ZMinus);
    }
    { Fl_Button* o = new Fl_Button(115, 80, 120, 30, "Pan+");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_PanPlus);
    }
    { Fl_Button* o = new Fl_Button(265, 80, 120, 30, "Pan-");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_PanMinus);
    }
    { Fl_Button* o = new Fl_Button(115, 115, 120, 30, "Tilt+");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_TiltPlus);
    }
    { Fl_Button* o = new Fl_Button(265, 115, 120, 30, "Tilt-");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_TiltMinus);
    }
    { Fl_Button* o = new Fl_Button(115, 150, 120, 30, "Roll+");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_RollPlus);
    }
    { Fl_Button* o = new Fl_Button(265, 150, 120, 30, "Roll-");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_RollMinus);
    }

      uiw->end();
  } // Fl_Double_Window* uiw
}

int main(int argc, char **argv) {
  scene = new Scene;
  return Fl::run();
}

void GUI::show() {
  uiw->show();
}

void GUI::DBG_cb() {
  scene->DBG();
}

void GUI::Play_cb() {
  scene->PlayButton();
}

void GUI::SM1_cb() {
    scene->SM1();
}

void GUI::SM2_cb() {
    scene->SM2();
}

void GUI::SM3_cb() {
    scene->SM3();
}

void GUI::AmbPlus_cb() {
    scene->AmbPlus();
}

void GUI::AmbMinus_cb() {
    scene->AmbMinus();
}

void GUI::SpecPlus_cb() {
    scene->SpecPlus();
}

void GUI::SpecMinus_cb() {
    scene->SpecMinus();
}

//old

void GUI::Left_cb(){
    scene->LeftButton();
}
void GUI::Right_cb(){
    scene->RightButton();
}
void GUI::Up_cb(){
    scene->UpButton();
}
void GUI::Down_cb(){
    scene->DownButton();
}
void GUI::Forward_cb(){
    scene->ForwardButton();
}
void GUI::Backward_cb(){
    scene->BackwardButton();
}

void GUI::ZPlus_cb(){
    scene->ZPlusButton();
}
void GUI::ZMinus_cb(){
    scene->ZMinusButton();
}

void GUI::TiltPlus_cb(){
    scene->TiltPlusButton();
}
void GUI::TiltMinus_cb(){
    scene->TiltMinusButton();
}
void GUI::PanPlus_cb(){
    scene->PanPlusButton();
}
void GUI::PanMinus_cb(){
    scene->PanMinusButton();
}
void GUI::RollPlus_cb(){
    scene->RollPlusButton();
}
void GUI::RollMinus_cb(){
    scene->RollMinusButton();
}
